bot:
  # todos los common pueden ser sobreescritos en cada banco, por ejemplo el selenium_port
  common: &common
    bot_url: "http://www.google.com"
    selenium_jar: "lib/selenium-server-standalone-2.0b3.jar"
    selenium_port: 4444
    selenium_host: localhost
    #selenium_browser: '*chrome'
    selenium_browser: '*chrome /home/nicolas/Downloads/firefox/firefox-bin'    
    mailer:
      mail_to: "njmery@gmail.com"
      #delivery_method: 'mutt' # si este es test no se envia mensajes si es mutt entonces no usa smtp_settings 
      delivery_method: 'test'
      smtp_settings:
        address:               "smtp.gmail.com"
        port:                   587
        user_name:             'insaciablesbot'
        password:              'pass'
        authentication:        'plain'
        enable_starttls_auto:   true
    restarts: 1
    loops: 1
    csv_filename: "cartola"
    csv_filepath: "cartolas/"
  aranceles:
    <<: *common
  
